// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, content string) (Note, error)
	DeleteNote(ctx context.Context, id int32) error
	GetNote(ctx context.Context, id int32) (Note, error)
	ListNotes(ctx context.Context) ([]Note, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
}

var _ Querier = (*Queries)(nil)
