// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (body) VALUES (?)
`

func (q *Queries) CreateMessage(ctx context.Context, body string) error {
	_, err := q.exec(ctx, q.createMessageStmt, createMessage, body)
	return err
}

const getMessages = `-- name: GetMessages :many
SELECT id, body, created_at, updated_at FROM messages ORDER BY created_at DESC
`

func (q *Queries) GetMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.query(ctx, q.getMessagesStmt, getMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
